#!/bin/sh
#-*- sh -*-

# some constants #
OUTPUT_NAME=bin/printf2
SERVER_MAIN=src/ServerMain.c
LIBRARIES="-lc -lm -lX11 bin/libenet.so.7 -Wl,-rpath,\$ORIGIN"
FLAGS="-fsanitize=address -g"
INCLUDES="-Ilib/enet/include"
##################

# internal vars dont touch #
ARGS=( $@ )
NARG=0
PROG_NAME=$0
############################

set -e

# $1 offset
getarg() {
  echo ${ARGS[$NARG + $1]}
}

argv() {
  R=${ARGS[@]:$NARG}
  echo ${R[@]}
}

target_build_enet() {
  make lib/enet
  cp lib/enet/.libs/libenet.so.7 bin
}

target_build() {
  mkdir -p bin
  target_build_enet
  echo cc $SERVER_MAIN $FLAGS $LIBRARIES $INCLUDES -o $OUTPUT_NAME
  cc $SERVER_MAIN $FLAGS $LIBRARIES $INCLUDES -o $OUTPUT_NAME
}

target_run() {
  target_build
  $OUTPUT_NAME `argv`
}

hasargs=1

# Fetch all sparse args
while [ $hasargs -eq 1 ]
do
  case `getarg 0` in
    *)
      hasargs=0
    ;;
  esac
done

case `getarg 0` in
  build)
    target_build
  ;;
  run)
    target_run
  ;;
  *)
    echo "You can do: run, build"
  ;;
esac


